### ISSUE TITLE
Break out OPA JSON test result -> JUnit XML conversion to separate library

### ISSUE THREAD

**Issue by anderseknert** [Bisnode/opa-gradle-plugin#10]
Design suggestion: `OpaToJunitConverter` could be a normal class with non-static methods, let's call it `OpaTestResult`. It could be created like `OpaTestResult.fromJson(String)`, then later in line 72 it could be used as `opaTestResult.toJUnitReport()` which would return `OpaJUnitReport`, so you can invoke `opaJUnitReport.writeTo(OutputStream)`. That's just a suggestion :)

_Originally posted by @lukasz-kaminski in https://github.com/Bisnode/opa-gradle-plugin/pull/9_

**Comment by anderseknert** [comment]
This is useful in contexts outside of Gradle (Maven, Bazel, standalone, etc), so would be good to not keep it hostage here.

**Comment by lukasz-kaminski** [comment]
Done. https://github.com/Bisnode/opa-test-result-formatter
