### ISSUE TITLE
Print "opa test -v" equivalent output to console

### ISSUE THREAD

**Issue by anderseknert** [Bisnode/opa-gradle-plugin#15]
While the JSON format is suitable for conversion to JUnit XML it's not very readable to humans. On test failures or verbose output settings, we should instead print the equivalent of "opa test -v" output. As we don't want to rerun the tests just for a different output format we should add a conversion from JSON to "opa test -v" style format.

```
data.nordicapis.test_allow_is_false_by_default: PASS (299.554µs)
data.nordicapis.test_allow_if_role_admin: PASS (13.895319ms)
data.nordicapis.test_allow_if_role_not_admin: PASS (525.143µs)
--------------------------------------------------------------------------------
PASS: 3/3
```

**Comment by lukasz-kaminski** [comment]
This can be done using our library https://github.com/Bisnode/opa-test-result-formatter

**Comment by anderseknert** [comment]
👍 ⭐
