### ISSUE TITLE
OPA process started with startOpa hangs  

### ISSUE THREAD

**Issue by k-jingyang** [Bisnode/opa-gradle-plugin#28]
Hey guys, thanks for making this plugin. :smile: It makes it much easier to run tests on CI pipelines. I've been using this and have noticed a possible bug? 

I realised that after using startOpa to start the OPA process, and running integration tests against it will cause the OPA process to hang (which causes the test to hang).  

[Here's the project to reproduce](https://github.com/k-jingyang/opa-plugin-spring-security)
Try running the `testHasAccessToResource` to see if it hangs.

I did some research, 
[java-process-builder-resultant-process-hangs](https://stackoverflow.com/questions/3285408/java-processbuilder-resultant-process-hangs)
[why-does-process-hang-if-the-parent-does-not-consume-stdout-stderr-in-java](https://stackoverflow.com/questions/16983372/why-does-process-hang-if-the-parent-does-not-consume-stdout-stderr-in-java)

It seems like the reason could be the plugin not consuming stdout and stderr from `Process` after creating it in `StartOpaTask.java`, thus filling up the buffer.  

I hacked out a [non-ideal solution](https://github.com/k-jingyang/opa-gradle-plugin/blob/master/src/main/java/com/bisnode/opa/StartOpaTask.java) to confirm my hypothesis by consuming stdout and stderr, and it seems to be working so far.

What do you guys think?

**Comment by lukasz-kaminski** [comment]
Thanks for filing the issue, we also appreciate the in-depth description :) We'll have a look at all this today, expect the fix to be released by Monday.

**Comment by lukasz-kaminski** [comment]
@k-jingyang Your research and description were extremely helpful, thanks for that! We'll need just a little bit more patience from your side, we need to iron out a few details :) Stay tuned!

**Comment by k-jingyang** [comment]
You're welcome! Glad to be a part of this! :smile:

**Comment by lukasz-kaminski** [comment]
This is now resolved in v0.3.1 which will be released today.
@anderseknert Thanks for the help with this.
@k-jingyang Thanks for the contribution and feel free to open more issues/PRs :)

**Comment by anderseknert** [comment]
0.3.1 now in the Gradle plugin repository https://plugins.gradle.org/plugin/com.bisnode.opa
